import type { Metadata } from "next";

import { Prompt } from 'next/font/google'

import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

const prompt = Prompt({
    subsets: ['latin'],
    weight: [
        '100', // Thin
        '200', // Extra Light
        '300', // Light
        '400', // Regular
        '500', // Medium
        '600', // Semi Bold
        '700', // Bold
        '800', // Extra Bold
        '900', // Black
    ],
    style: ['normal', 'italic'],
    variable: '--font-prompt',
    display: 'swap',
})


export const metadata: Metadata = {
    title: "Skylight Village",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${prompt.className} antialiased`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
